image: node:lts-alpine

cache:
  paths:
    - node_modules/

deploy:
  stage: deploy
  script:
    # Install prereqs
    - apk --no-cache add tree
    - apk --no-cache add wput --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing
    - npm install -g pnpm

    # Build project
    - pnpm
    - pnpm build
    - tree -h ./public

    # Push build to prod
    - wput --less-verbose --reupload --dont-continue --basename=public/ public/* "$GIT_FTP_URL"

  artifacts:
    paths:
      - public

  only:
    - master
