image: node:lts

cache:
  paths:
    - node_modules/

deploy:
  stage: deploy
  script:
    # Install prereqs
    - apt-get update
    - apt-get install -yqq make git tree wput
    # Clean apt cache
    - apt-get clean
    - rm -rf /var/lib/apt/lists/*

    # Build project
    - yarn
    - yarn build
    - tree -h ./public

    # Push build to prod
    - wput --quiet --reupload --basename=public/ public/* "$GIT_FTP_URL"

  artifacts:
    paths:
      - public

  only:
    - master
